### PR TITLE
fix(filter): Do not emit filter add even when filter value is empty

### LINKED ISSUE #124: Filter should not be added when field value is empty
In Angular PatternFly:
https://github.com/patternfly/angular-patternfly/blob/a07d2c78263e6dc41f342eaf041d47096b9c6dcf/src/filters/simple-filter/filter-fields-component.js#L92-L93

While in PatternFly-ng:
https://github.com/patternfly/patternfly-ng/blob/5535abd79692aade228b4d20ca4ea5636e7daa82/src/app/filter/filter-fields.component.ts#L147-L151

### PR DESCRIPTION
**Pull request by astefanutti**
fixes #124

### CODE REVIEW

**Review by dlabrecq — COMMENTED** [review]
We will need to test this still works with type ahead functionality.

**Review by dlabrecq — APPROVED** [review]
This change was just introduced to Angular Patternfly on 8/23.

See: https://github.com/patternfly/angular-patternfly/pull/593

Although patternfly-ng does not generate a similar null.legnth error, it does allow an empty filter.

**Comment by astefanutti** [comment]
Is there anything else that should be done on my side?

**Comment by dlabrecq** [comment]
Just needed two people to review. Thanks for the fix!

**Comment by astefanutti** [comment]
Thanks for the new release 👍

**Pull request merged**
