### PR TITLE
Add support for UMD and es2015 bundles

### PR DESCRIPTION
**Pull request by dlabrecq**
This is a work in progress, but I've added support for UMD and es2015 bundles. Needs further testing with a SystemJS based application.

Fixes: https://github.com/patternfly/patternfly-ng/issues/366

### CODE REVIEW

**Comment by dlabrecq** [comment]
Modified a SystemJS based application (using Stan's 'Tour of Heros' app) for testing. The changes for this example can be seen here:
https://github.com/dlabrecq/angular-tour-of-heroes/pull/1/files

Omitted dependencies from UMD and es2015 bundles (e.g., c3, d3, ngx-bootstrap, ngx-datatable, etc.), which allows the application to install different versions.

Unlike ES6 modules, the test application required all dependencies to be installed. It's not clear if that's something that can be changed with the example application?

**Comment by dlabrecq** [comment]
FYI @ssilvert

**Comment by dlabrecq** [comment]
I was able to omit unused dependencies by mapping c3, angular-tree-component, etc. to '@empty', for example. The example app has been updated here: https://github.com/dlabrecq/angular-tour-of-heroes/pull/1/files

**Review by seanforyou23 — APPROVED** [review]
Works for me, tried using a SystemJS app as well as an app running angular + angular cli, was able to consume the entire patternfly-ng library, or individual pfng modules without issue.

LGTM - nice work!

**Comment by dlabrecq** [comment]
Per @ssilvert 's suggestion, I've removed the babel plugin from the example application and everything worked as expected. Unless there are any further comments, I'll merge shortly?

**Comment by ssilvert** [comment]
Sounds great, Dan.  Please let me know when there is a build I can try out.

**Pull request merged**
