### PR TITLE
Demo: navigation layout based on patternfly.org

### PR DESCRIPTION
**Pull request by dlabrecq**
Added a new navigation layout for the demo based on patternfly.org.

Note that this layout is responsive. When the window shrinks, the primary nav is replaced with a hamburger icon. The user can then navigate all primary menu items via the side bar.

Fixes: https://github.com/patternfly/patternfly-ng/issues/223

Example:
https://rawgit.com/dlabrecq/patternfly-ng/navbar-dist/dist-demo/

### CODE REVIEW

**Review by dgutride — DISMISSED** [review]

**Comment by dgutride** [comment]
I like it - only thought was I couldn't find the components at first, might be good to get one of the designers to weigh in on the layout, too?

**Comment by AdamJ** [comment]
Would it make sense to have the structure of the vertical navigation match (or closely resemble) PatternFly.org, to keep some continuity between the two?

**Comment by dlabrecq** [comment]
I didn't follow patternfly.org verbatium because its categories make it very difficult to find components. However, I've changed things up a bit. You can now navigate anywhere from Get Started, which is also the landing page. 

In addition, I added selection highlighting which seems to help a lot.

Get Started:
screen shot 2017-12-14 at 11 43 38 am

Components:
screen shot 2017-12-14 at 11 43 57 am

**Comment by seanforyou23** [comment]
Looks great! One thing I noticed is the menu doesn't update itself when the browser back button is used. Similarly, if I navigate to a component using the menu and then click the logo in the top left corner, the menu doesn't reflect that we're now on the home view. It does however update itself when clicking the heading (.secondary-menu-toggle) at the top of the menu, though the cursor isn't a pointer so it isn't so obvious.

**Comment by dlabrecq** [comment]
Thanks @seanforyou23. The browser back button never worked for the existing demo -- the selected item in the navigation pane never changes. Regardless, I've added support for the browser back button and it seems to work well now.

I've also spoken to @mindreeper2420 offline. Per his comments, I've removed the 200px, left-side margin to fix the layout on mobile.

**Review by AdamJ — APPROVED** [review]

**Pull request merged**
