### PR TITLE
feat(notification): add inline notification component

### PR DESCRIPTION
**Pull request by dgutride**
Also includes a little improvement for karma tests

### CODE REVIEW

**Comment by dgutride** [comment]
Example here for design review
https://rawgit.com/dgutride/patternfly-ng/inline-notification-dist/dist-demo/#/inlinenotification

**Review by dlabrecq — APPROVED** [review]
LGTM

**Comment by dgutride** [comment]
@mindreeper2420  - can I get a second look before we merge?

**Comment by AdamJ** [comment]
@dgutride If I remove the Header and Message, the icon no longer sits inside of the block
screen shot 2017-09-05 at 10 06 13 am

**Comment by dgutride** [comment]
@mindreeper2420 -  is that a bug with the patternfly classes being used?  I don't know what we'd do about that in here.

**Comment by AdamJ** [comment]
@dgutride looks like it is - `position: absolute;` of the icon placement. I'll file an issue/question on PF Core.

**Review by AdamJ — APPROVED** [review]

**Pull request merged**
